###
GET http://localhost:3000/api/pix/payment/vfdtr3wu
###
GET http://localhost:3000/api/pix/create/link/26558
content-type: application/json

{
    "Date_int": "2024-02-20.00:00:00T",
    "Status_pg": "Em Aberto"
}